# Generated by Django 5.1.4 on 2024-12-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_rename_date_news_created_at_alter_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='description',
        ),
    ]
